### ISSUE TITLE
Incorporate a nice looking theme

### ISSUE THREAD

**Issue by pradyunsg** [python-gsoc/python-gsoc.github.io#39]
I'm want to work on giving this website a more modern feel, not now but a few weeks down the line.

I just want to make sure that no one would mind me working on it. Also, is there's anyone I could ping if I stumble upon some issue? :)

**Comment by terriko** [comment]
Honestly, I think this would be a poor use of your volunteer time and talent; no one's going to be excited about working on this with you over the next few months (we need a break from GSoC wrap-up!), and I'm personally going to be exceedingly cranky due to lack of sleep.  If you're looking for website work and interested in theming, there are lots of other projects that will be more active and appreciative during this time!

**Comment by pradyunsg** [comment]
Sounds reasonable to me. FWIW, I was thinking of switching the site to the
pydoc theme (the official documentation), in line with what pypa is
doing/done.

GSoC was awesome this year. Thank you for that! :)
